language: python
python: 2.7
sudo: false
env:
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=docs
install:
- pip install tox
script:
- tox -e $TOX_ENV
after_success:
- if [[ "${TOX_ENV}" == "py27" ]]; then tox -e coveralls; fi
notifications:
  email: false
